import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "./ui/components/header/header";
import { Providers } from "./providers";
import Footer from "./ui/components/footer/footer";

export const metadata = {
  title: "Crea Jovem",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export default function RootLayout({ children }) {
  return (
    <html lang="pt">
      <body
        className={`antialiased text-creajovem-blue-700 dark:text-white ${montserrat.className}`}
      >
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
